// Europa
export { default as AD } from './AD - Andorra.svg?react'
export { default as AL } from './AL - Albania.svg?react'
export { default as AM } from './AM - Armenia.svg?react'
export { default as AT } from './AT - Austria.svg?react'
export { default as AX } from './AX - Aland Islands.svg?react'
export { default as AZ } from './AZ - Azerbaijan.svg?react'
export { default as BA } from './BA - Bosnia and Herzegovina.svg?react'
export { default as BE } from './BE - Belgium.svg?react'
export { default as BG } from './BG - Bulgaria.svg?react'
export { default as BY } from './BY - Belarus.svg?react'
export { default as CH } from './CH - Switzerland.svg?react'
export { default as CY } from './CY - Cyprus.svg?react'
export { default as CZ } from './CZ - Czech Republic.svg?react'
export { default as DE } from './DE - Germany.svg?react'
export { default as DK } from './DK - Denmark.svg?react'
export { default as EE } from './EE - Estonia.svg?react'
export { default as ES } from './ES - Spain.svg?react'
export { default as FI } from './FI - Finland.svg?react'
export { default as FR } from './FR - France.svg?react'
export { default as GB_ENG } from './GB-ENG - England.svg?react'
export { default as GB_NIR } from './GB-NIR - Northern Ireland.svg?react'
export { default as GB_SCT } from './GB-SCT - Scotland.svg?react'
export { default as GB_UKM } from './GB-UKM - United Kingdom.svg?react'
export { default as GB_WLS } from './GB-WLS - Wales.svg?react'
export { default as GE } from './GE - Georgia.svg?react'
export { default as GG } from './GG - Guernsey.svg?react'
export { default as GI } from './GI - Gibraltar.svg?react'
export { default as GR } from './GR - Greece.svg?react'
export { default as HR } from './HR - Croatia (Hrvatska).svg?react'
export { default as HU } from './HU - Hungary.svg?react'
export { default as IE } from './IE - Ireland.svg?react'
export { default as IM } from './IM - Isle of Man.svg?react'
export { default as IS } from './IS - Iceland.svg?react'
export { default as IT } from './IT - Italy.svg?react'
export { default as JE } from './JE - Jersey.svg?react'
export { default as LI } from './LI - Liechtenstein.svg?react'
export { default as LT } from './LT - Lithuania.svg?react'
export { default as LU } from './LU - Luxembourg.svg?react'
export { default as LV } from './LV - Latvia.svg?react'
export { default as MC } from './MC - Monaco.svg?react'
export { default as MD } from './MD - Moldova.svg?react'
export { default as ME } from './ME - Montenegro.svg?react'
export { default as MK } from './MK - North Macedonia.svg?react'
export { default as MT } from './MT - Malta.svg?react'
export { default as NL } from './NL - Netherlands.svg?react'
export { default as NO } from './NO - Norway.svg?react'
export { default as PL } from './PL - Poland.svg?react'
export { default as PT } from './PT - Portugal.svg?react'
export { default as RO } from './RO - Romania.svg?react'
export { default as RS } from './RS - Serbia.svg?react'
export { default as RU } from './RU - Russian Federation.svg?react'
export { default as SE } from './SE - Sweden.svg?react'
export { default as SI } from './SI - Slovenia.svg?react'
export { default as SK } from './SK - Slovakia.svg?react'
export { default as SM } from './SM - San Marino.svg?react'
export { default as UA } from './UA - Ukraine.svg?react'
export { default as VA } from './VA - Vatican City State.svg?react'

// Américas
export { default as AR } from './AR - Argentina.svg?react'
export { default as BO } from './BO - Bolivia.svg?react'
export { default as BR } from './BR - Brazil.svg?react'
export { default as CA } from './CA - Canada.svg?react'
export { default as CL } from './CL - Chile.svg?react'
export { default as CO } from './CO - Colombia.svg?react'
export { default as CR } from './CR - Costa Rica.svg?react'
export { default as CU } from './CU - Cuba.svg?react'
export { default as DO } from './DO - Dominican Republic.svg?react'
export { default as EC } from './EC - Ecuador.svg?react'
export { default as GT } from './GT - Guatemala.svg?react'
export { default as HN } from './HN - Honduras.svg?react'
export { default as MX } from './MX - Mexico.svg?react'
export { default as NI } from './NI - Nicaragua.svg?react'
export { default as PA } from './PA - Panama.svg?react'
export { default as PE } from './PE - Peru.svg?react'
export { default as PR } from './PR - Puerto Rico.svg?react'
export { default as PY } from './PY - Paraguay.svg?react'
export { default as SV } from './SV - El Salvador.svg?react'
export { default as US } from './US - United States.svg?react'
export { default as UY } from './UY - Uruguay.svg?react'
export { default as VE } from './VE - Venezuela.svg?react'

// África
export { default as AO } from './AO - Angola.svg?react'
export { default as DZ } from './DZ - Algeria.svg?react'
export { default as EG } from './EG - Egypt.svg?react'
export { default as ET } from './ET - Ethiopia.svg?react'
export { default as GH } from './GH - Ghana.svg?react'
export { default as KE } from './KE - Kenia.svg?react'
export { default as MA } from './MA - Morocco.svg?react'
export { default as NG } from './NG - Nigeria.svg?react'
export { default as SD } from './SD - Sudan.svg?react'
export { default as SS } from './SS - South Sudan.svg?react'
export { default as TN } from './TN - Tunisia.svg?react'
export { default as ZA } from './ZA - South Africa.svg?react'
export { default as ZM } from './ZM - Zambia.svg?react'
export { default as ZW } from './ZW - Zimbabwe.svg?react'

// Ásia
export { default as AE } from './AE - United Arab Emirates.svg?react'
export { default as AF } from './AF - Afghanistan.svg?react'
export { default as BD } from './BD - Bangladesh.svg?react'
export { default as CN } from './CN - China.svg?react'
export { default as HK } from './HK - Hong Kong.svg?react'
export { default as ID } from './ID - Indonesia.svg?react'
export { default as IN } from './IN - India.svg?react'
export { default as IQ } from './IQ - Iraq.svg?react'
export { default as IR } from './IR - Iran.svg?react'
export { default as JP } from './JP - Japan.svg?react'
export { default as KR } from './KR - Korea (South).svg?react'
export { default as KP } from './KP - Korea (North).svg?react'
export { default as MY } from './MY - Malaysia.svg?react'
export { default as PH } from './PH - Philippines.svg?react'
export { default as PK } from './PK - Pakistan.svg?react'
export { default as QA } from './QA - Qatar.svg?react'
export { default as SA } from './SA - Saudi Arabia.svg?react'
export { default as SG } from './SG - Singapore.svg?react'
export { default as TH } from './TH - Thailand.svg?react'
export { default as TR } from './TR - Turkey.svg?react'
export { default as TW } from './TW - Taiwan.svg?react'
export { default as VN } from './VN - Vietnam.svg?react'

// Oceania
export { default as AU } from './AU - Australia.svg?react'
export { default as NZ } from './NZ - New Zealand (Aotearoa).svg?react'
